services:
  - type: web
    name: sartaj-security
    env: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: "/sign-in"
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
        value: "/admin/dashboard"
      - key: ADMIN_USER_ID
        sync: false
      - key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
        sync: false
      - key: NEXT_PUBLIC_CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
